---
- name: Set up user environment
  hosts: all
  become: yes
  
  vars_prompt:
    - name: target_user
      prompt: Enter the target username
      private: no
      default: "{{ lookup('pipe', 'whoami') }}"
    - name: target_user_home_dir
      prompt: Enter the target user's home directory
      private: no
      default: "{{ lookup('env', 'HOME') }}"

  tasks:
    - name: Check if user has sudo permissions or is root
      command: sudo -n true
      register: sudo_result
      ignore_errors: yes
      changed_when: false

    - name: Abort if user doesn't have sudo permissions and is not root
      fail:
        msg: "This playbook requires sudo permissions or root access. Please run with sudo or as root."
      when: sudo_result.rc != 0 and ansible_user_id != 'root'

    - name: Ensure target user exists
      user:
        name: "{{ target_user }}"
        state: present
        create_home: yes
        home: "{{ target_user_home_dir }}"

    - name: Ensure target user's home directory exists
      file:
        path: "{{ target_user_home_dir }}"
        state: directory
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0755'

    - name: Check if Oh My Bash is installed and save path
      block:
      - name: Check if $OSH is set
        shell: echo $OSH
        register: osh_var
        changed_when: false
        ignore_errors: yes

      - name: Check if /usr/local/share/oh-my-bash exists
        stat:
          path: /usr/local/share/oh-my-bash
        register: osh_install_dir

      - name: Set fact for Oh My Bash path from $OSH
        set_fact:
          osh_path: "{{ osh_var.stdout }}"
        when: osh_var.stdout != ""

      - name: Set fact for Oh My Bash path from directory
        set_fact:
          osh_path: "/usr/local/share/oh-my-bash"
        when: osh_install_dir.stat.exists and osh_var.stdout == ""

      - name: Abort if Oh My Bash is not installed
        fail:
          msg: "Oh My Bash is not installed. Please install it before running this playbook."
        when: 
          - osh_var.stdout == ""
          - not osh_install_dir.stat.exists

    - name: Set fact for variables to be used in imported playbooks
      set_fact:
        shared_vars:
          target_user: "{{ target_user }}"
          target_user_home_dir: "{{ target_user_home_dir }}"
          osh_install_dir: "{{ osh_install_dir }}"

    - name: Display user information
      debug:
        msg:
          - "Target User: {{ target_user }}"
          - "Home Directory: {{ target_user_home_dir }}"
          - "Oh-My-Bash Install Directory: {{ osh_install_dir }}"

- import_playbook: user_env_update.yml
  vars:
    osh_install_dir: "{{ hostvars['localhost']['shared_vars']['osh_install_dir'] }}"
    target_user: "{{ hostvars['localhost']['shared_vars']['target_user'] }}"
    target_user_home_dir: "{{ hostvars['localhost']['shared_vars']['target_user_home_dir'] }}"
