---
- name: Set up user environment
  hosts: all
  become: no
  
  pre_tasks:
    - name: Check if sudo is available
      command: which sudo
      register: sudo_available
      ignore_errors: yes
      changed_when: false

    - name: Test sudo access
      command: sudo -n true
      register: sudo_test
      ignore_errors: yes
      changed_when: false
      when: sudo_available.rc == 0

    - name: Set facts about sudo status
      set_fact:
        has_sudo: "{{ sudo_available.rc == 0 and sudo_test.rc == 0 }}"

    - name: Fail if no sudo access available
      fail:
        msg: |
          This playbook requires sudo access for system-wide installation.
          Please ensure you have sudo rights or run with sudo.
          Current status:
          - Sudo available: {{ sudo_available.rc == 0 }}
          - Sudo access: {{ sudo_test.rc == 0 if sudo_available.rc == 0 else 'N/A' }}
      when: not has_sudo

- name: System-wide setup
  import_playbook: system_setup.yml

- name: Package installation
  import_playbook: packages_install.yml

- name: Oh-My-Bash setup
  import_playbook: oh-my-bash_setup.yml

- name: User environment setup
  import_playbook: user_env_setup.yml
  vars:
    target_user: "{{ lookup('env', 'USER') }}"
    target_user_home: "{{ lookup('env', 'HOME') }}"

- name: Version check and update
  import_playbook: version_check.yml
