---
- name: Set up user environment
  hosts: all
  become: yes
  
  vars_prompt:
    - name: target_user
      prompt: Enter the target username
      private: no
      default: "{{ lookup('pipe', 'whoami') }}"
    - name: target_user_home
      prompt: Enter the target user's home directory
      private: no
      default: "{{ lookup('env', 'HOME') }}"

  tasks:
    - name: Check if user has sudo permissions or is root
      command: sudo -n true
      register: sudo_result
      ignore_errors: yes
      changed_when: false

    - name: Abort if user doesn't have sudo permissions and is not root
      fail:
        msg: "This playbook requires sudo permissions or root access. Please run with sudo or as root."
      when: sudo_result.rc != 0 and ansible_user_id != 'root'

    - name: Display setup information
      debug:
        msg:
          - "Target User: {{ target_user }}"
          - "Home Directory: {{ target_user_home }}"
          - "Oh-My-Bash Directory: /usr/local/share/oh-my-bash"

- import_playbook: version_check.yml
- import_playbook: packages_install.yml
- import_playbook: oh-my-bash_setup.yml
  vars:
    target_user: "{{ hostvars['localhost']['target_user'] }}"
    target_user_home: "{{ hostvars['localhost']['target_user_home'] }}"
- import_playbook: user_env_setup.yml
  vars:
    target_user: "{{ hostvars['localhost']['target_user'] }}"
    target_user_home: "{{ hostvars['localhost']['target_user_home'] }}"
