---
- name: Set up user environment
  hosts: all
  become: yes
  vars_prompt:
    - name: target_user
      prompt: Enter the target username
      private: no
      default: "{{ lookup('env', 'USER') }}"

  tasks:
    - name: Ensure target user exists
      user:
        name: "{{ target_user }}"
        state: present
        create_home: yes

- import_playbook: packages_install.yml
- import_playbook: oh-my-bash_setup.yml
- import_playbook: user_setup.yml