---
- name: Set up Oh-My-Bash system-wide
  hosts: all
  become: yes

  tasks:
    # Install oh-my-bash
    - name: Install Oh-My-Bash system-wide
      shell: >
        bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)" --prefix=/usr/local --unattended
      args:
        creates: /usr/local/share/oh-my-bash/oh-my-bash.sh

    # Theme setup
    - name: Ensure custom theme directories exist
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        mode: '0775'
      loop:
        - /usr/local/share/oh-my-bash/custom
        - /usr/local/share/oh-my-bash/custom/themes
        - /usr/local/share/oh-my-bash/custom/themes/luan

    - name: Copy custom luan theme
      copy:
        src: "../../configs/oh-my-bash/themes/luan/luan.theme.sh"
        dest: "/usr/local/share/oh-my-bash/custom/themes/luan/luan.theme.sh"
        owner: root
        mode: '0664'
        force: yes

    # Set temporary environment variables for the current Ansible run
    - name: Set OSH environment variables for current session
      set_fact:
        ansible_env: "{{ ansible_env | combine({
          'OSH': '/usr/local/share/oh-my-bash',
          'OSH_CUSTOM': '/usr/local/share/oh-my-bash/custom'
        }) }}"
