---
- name: Set up Oh-My-Bash system-wide
  hosts: all
  become: yes

  tasks:
    - name: Install Oh-My-Bash system-wide
      shell: >
        cd ~ && bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)" --prefix=/usr/local --unattended
      args:
        creates: /usr/local/share/oh-my-bash

    - name: Ensure custom theme directories exist
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /usr/local/share/oh-my-bash/custom
        - /usr/local/share/oh-my-bash/custom/themes
        - /usr/local/share/oh-my-bash/custom/themes/luan

    - name: Copy custom luan theme
      copy:
        src: "../../configs/oh-my-bash/themes/luan/luan.theme.sh"
        dest: "/usr/local/share/oh-my-bash/custom/themes/luan/luan.theme.sh"
        mode: '0644'
        force: yes

    - name: Create system-wide oh-my-bash configuration
      copy:
        dest: /etc/profile.d/oh-my-bash.sh
        content: |
          # System-wide oh-my-bash configuration
          export OSH='/usr/local/share/oh-my-bash'
          export OSH_CUSTOM='/usr/local/share/oh-my-bash/custom'
          [ -f $OSH/oh-my-bash.sh ] && source $OSH/oh-my-bash.sh
        mode: '0644'

    # Set temporary environment variables for the current Ansible run
    - name: Set OSH environment variables for current session
      set_fact:
        ansible_env: "{{ ansible_env | combine({
          'OSH': '/usr/local/share/oh-my-bash',
          'OSH_CUSTOM': '/usr/local/share/oh-my-bash/custom'
        }) }}"
