---
- name: Set up Oh-My-Bash for target user
  hosts: all
  become: yes

  tasks:
    - name: Install Oh-My-Bash system-wide
      shell: >
        cd ~ && bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)" --prefix=/usr/local --unattended
      args:
        creates: "{{ osh_install_dir }}"

    - name: Set global variables
      lineinfile:
        path: /etc/environment
        line: "{{ item }}"
      loop:
        - "OSH={{ osh_install_dir }}"

    - name: Create luan theme directory
      file:
        path: "{{ osh_install_dir }}/themes/luan"
        state: directory
        mode: '0755'

    - name: Copy custom luan theme to themes
      copy:
        src: ../../themes/oh-my-bash/luan-custom.theme.sh
        dest: "{{ osh_install_dir }}/themes/luan/luan.theme.sh"
        mode: '0644'
        force: yes

