---
- name: Set up Oh-My-Bash for target user
  hosts: all
  become: yes
  vars:
    osh_install_dir: /usr/local/share/oh-my-bash
    target_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
    user_home_dir: "{{ lookup('env', 'HOME') }}"

  tasks:
    - name: Install Oh-My-Bash system-wide
      shell: >
        bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)" --prefix=/usr/local
      args:
        creates: "{{ osh_install_dir }}"

    - name: Set global variables
      lineinfile:
        path: /etc/environment
        line: "{{ item }}"
      loop:
        - "OSH={{ osh_install_dir }}"

    - name: Create luan theme directory
      file:
        path: "{{ osh_install_dir }}/themes/luan"
        state: directory
        mode: '0755'

    - name: Copy custom luan theme to themes
      copy:
        src: ../../themes/oh-my-bash/luan-custom.theme.sh
        dest: "{{ osh_install_dir }}/themes/luan/luan.theme.sh"
        mode: '0644'
        force: yes

    - name: Copy .custom.bashrc to user's home directory
      copy:
        src: ../../configs/.custom.bashrc
        dest: "{{ user_home_dir }}/.custom.bashrc"
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0644'

    - name: Copy .custom.bash_profile to user's home directory
      copy:
        src: ../../configs/.custom.bash_profile
        dest: "{{ user_home_dir }}/.custom.bash_profile"
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0644'

    - name: Ensure .custom.bashrc is sourced in user's .bashrc
      blockinfile:
        path: "{{ user_home_dir }}/.bashrc"
        block: |
          # Oh-My-Bash configuration
          export OSH='{{ osh_install_dir }}'
          
          # Source custom bashrc if it exists
          if [ -f ~/.custom.bashrc ]; then
              source ~/.custom.bashrc
          fi
        marker: "# {mark} ANSIBLE MANAGED BLOCK - OH-MY-BASH"
        create: yes
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0644'

    - name: Ensure .custom.bash_profile is sourced in user's .bash_profile
      blockinfile:
        path: "{{ user_home_dir }}/.bash_profile"
        block: |
          # Source custom bash_profile if it exists
          if [ -f ~/.custom.bash_profile ]; then
              source ~/.custom.bash_profile
          fi
        marker: "# {mark} ANSIBLE MANAGED BLOCK - OH-MY-BASH"
        create: yes
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0644'