---
- name: Install required packages
  hosts: all
  become: yes

  tasks:
    - name: Update package cache (Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install required packages (Debian/Ubuntu)
      apt:
        name:
          - tmux
          - zip
          - unzip
          - btop
          - htop
          - wget
          - curl
          - ncdu
          - bat
          - ncdu
          - fzf
        state: present
      when: ansible_os_family == "Debian"
