---
- name: Install required packages
  hosts: all
  become: yes

  tasks:
    - name: Update package cache (Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install required packages (Debian/Ubuntu)
      apt:
        name:
          - git
          - vim
          - tmux
          # Add other packages you need
        state: present
      when: ansible_os_family == "Debian"

    - name: Install required packages (RedHat/CentOS)
      yum:
        name:
          - git
          - vim
          - tmux
          # Add other packages you need
        state: present
      when: ansible_os_family == "RedHat"