---
- name: Configure system-wide components
  hosts: all
  become: yes  # These tasks need sudo
  vars:
    target_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"

  tasks:
    # Group setup
    - name: Create osh group
      group:
        name: osh
        state: present

    - name: Debug user detection
      debug:
        msg: 
          - "Target user: {{ target_user }}"
          - "Sudo user: {{ ansible_env.SUDO_USER | default('not set') }}"
          - "User ID: {{ ansible_user_id }}"

    - name: Add current user to osh group
      user:
        name: "{{ target_user }}"
        groups: osh
        append: yes

    # Create base directories with proper ownership
    - name: Ensure oh-my-bash base directory exists
      file:
        path: /usr/local/share/oh-my-bash
        state: directory
        owner: root
        group: osh
        mode: '0775'

    - name: Create system-wide environment file
      copy:
        dest: /etc/profile.d/oh-my-bash.sh
        content: |
          # System-wide oh-my-bash configuration
          export OSH='/usr/local/share/oh-my-bash'
          export OSH_CUSTOM='/usr/local/share/oh-my-bash/custom'
          [ -f $OSH/oh-my-bash.sh ] && source $OSH/oh-my-bash.sh
        owner: root
        group: root
        mode: '0644'
        