---
- name: Configure system-wide components
  hosts: all
  become: yes
  vars:
    target_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"

  tasks:
    # Existing tasks...
    - name: Create system-wide environment file
      copy:
        dest: /etc/profile.d/oh-my-bash.sh
        content: |
          # System-wide oh-my-bash configuration
          export OSH='/usr/local/share/oh-my-bash'
          export OSH_CUSTOM='/usr/local/share/oh-my-bash/custom'
          [ -f $OSH/oh-my-bash.sh ] && source $OSH/oh-my-bash.sh
        owner: root
        group: root
        mode: '0644'

    # New timezone configuration
    - name: Install required packages for timezone setup
      apt:
        name:
          - systemd
          - tzdata
        state: present

    - name: Set timezone to Europe/Berlin
      community.general.timezone:
        name: Europe/Berlin

    - name: Enable NTP
      command: timedatectl set-ntp true
      changed_when: false
      failed_when: false  # Some systems might not support NTP
