---
- name: Update user environment
  hosts: all
  become: yes
  vars:
    target_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
    target_user_home: "{{ ansible_env.HOME }}"

  tasks:
    # Config Updates (No migration needed)
    - name: Update bashrc and aliases
      copy:
        src: "../../configs/{{ item }}"
        dest: "{{ target_user_home }}/.automated-user-env/{{ item }}"
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0644'
      loop:
        - bashrc
        - bash_profile

    # Package Updates (No migration needed)
    - name: Install/Update packages
      apt:
        name: "{{ system_packages }}"
        state: present
        update_cache: yes

    # Check for pending migrations
    - name: Check pending migrations
      include_tasks: check_migrations.yml

    # Force reload of shell configuration
    - name: Reload shell configuration
      shell: |
        exec bash
        source {{ target_user_home }}/.bashrc
      become_user: "{{ target_user }}"
