---
- name: Configure user environment
  hosts: all
  become: yes
  vars:
    target_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
    target_user_home_dir: "{{ lookup('env', 'HOME') }}"

  tasks:
    - name: Copy custom dotfiles
      copy:
        src: "../../configs/{{ item }}"
        dest: "{{ target_user_home_dir }}/{{ item }}"
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0644'
      loop:
        - .custom.bashrc
        - .custom.bash_profile

    - name: Ensure custom bashrc is sourced in .bashrc
      lineinfile:
        path: "{{ target_user_home_dir }}/.bashrc"
        line: "[ -f ~/.custom.bashrc ] && source ~/.custom.bashrc"
        create: yes

    - name: Ensure custom bash_profile is sourced in .bash_profile
      lineinfile:
        path: "{{ target_user_home_dir }}/.bash_profile"
        line: "[ -f ~/.custom.bash_profile ] && source ~/.custom.bash_profile"
        create: yes
