---
- name: Update user environment
  hosts: all
  become: yes
  vars:
    target_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"

  tasks:
    - name: Update custom theme
      copy:
        src: ../../themes/oh-my-bash/luan-custom.theme.sh
        dest: "{{ osh_install_dir }}/themes/luan/luan.theme.sh"
        mode: '0644'
        force: yes

    - name: Update custom dotfiles
      copy:
        src: "../../configs/{{ item }}"
        dest: "{{ target_user_home_dir }}/{{ item }}"
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0644'
      loop:
        - .custom.bashrc
        - .custom.bash_profile

    # Add more tasks to update other custom configurations as needed

    - name: Reload bash configuration
      shell: source {{ target_user_home_dir }}/.bashrc
      become_user: "{{ target_user }}"