---
- name: Configure user environment
  hosts: all
  become: yes

  tasks:
    - name: Copy custom dotfiles
      copy:
        src: "../../configs/{{ item }}"
        dest: "{{ target_user_home_dir }}/{{ item }}"
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0644'
      loop:
        - .custom.bashrc
        - .custom.bash_profile

    - name: Set global variables
      lineinfile:
        path: /etc/environment
        line: "{{ item }}"
      loop:
        - "OSH={{ osh_install_dir }}"

    - name: Ensure oh-my-bash is sourced in .bashrc
      blockinfile:
        path: "{{ target_user_home_dir }}/.bashrc"
        block: |

          # Oh-My-Bash configuration
          export OSH='{{ osh_install_dir }}'

        marker: "# {mark} ANSIBLE MANAGED BLOCK - OH-MY-BASH"
        create: yes
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0644'

    - name: Ensure .custom.bashrc is sourced in user's .bashrc
      blockinfile:
        path: "{{ target_user_home_dir }}/.bashrc"
        block: |
          # Source custom bashrc if it exists
          if [ -f ~/.custom.bashrc ]; then
              source ~/.custom.bashrc
          fi

        create: yes
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0644'

    - name: Ensure .custom.bash_profile is sourced in user's .bash_profile
      blockinfile:
        path: "{{ target_user_home_dir }}/.bash_profile"
        block: |
          # Source custom bash_profile if it exists
          if [ -f ~/.custom.bash_profile ]; then
              source ~/.custom.bash_profile
          fi

        marker: "# {mark} ANSIBLE MANAGED BLOCK - OH-MY-BASH"
        create: yes
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0644'

    - name: Reload bash configuration
      shell: source {{ target_user_home_dir }}/.bashrc
      become_user: "{{ target_user }}"