---
- name: Update user environment
  hosts: all
  become: yes
  vars:
    target_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"

  tasks:
    - name: Update Oh-My-Bash
      git:
        repo: https://github.com/ohmybash/oh-my-bash.git
        dest: "/home/{{ target_user }}/.oh-my-bash"
        update: yes
      become_user: "{{ target_user }}"

    - name: Update custom theme
      copy:
        src: ../../themes/custom_oh_my_bash_theme.sh
        dest: "/home/{{ target_user }}/.oh-my-bash/custom/themes/custom_theme.sh"
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0644'

    - name: Update custom dotfiles
      copy:
        src: "../../configs/{{ item }}"
        dest: "/home/{{ target_user }}/{{ item }}"
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0644'
      loop:
        - .custom.bashrc
        - .custom.bash_profile

    # Add more tasks to update other custom configurations as needed

    - name: Reload bash configuration
      shell: source /home/{{ target_user }}/.bashrc
      become_user: "{{ target_user }}"